### ISSUE TITLE
编译失败，log提示 JRMemory.framework 缺少依赖如何解决

### ISSUE THREAD

**Issue by yycmd** [nongshifu/Smoba#1]
如下图所示，缺少一个或更多依赖，我看了看框架内的 头文件好像也没啥问题，都是引用标准库

![QQ20230128-165534](https://user-images.githubusercontent.com/17695132/215257037-59002e77-1f7a-4885-b02f-0ddf5da02750.png)

**Comment by nongshifu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
我很忙可能没时间回你邮件哦

**Comment by yy981420974** [comment]
问题已经解决了，在 build setting --> architectures --> Excluded Architectures 中填写 arm64e 即可编译通过
![Jietu20230129-160433](https://user-images.githubusercontent.com/17695132/215313487-23297b02-fb44-468b-b96d-d55db032716d.jpg)

**Comment by yy981420974** [comment]
问题已解决

**Comment by nongshifu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
我很忙可能没时间回你邮件哦

**Comment by nongshifu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
我很忙可能没时间回你邮件哦
